import os

NAME = "GingerJs"
VERSION = "1.0"
PACKAGE_MANAGER = "yarn",
DEBUG = False
PORT = "5001"
HOST   = "0.0.0.0"
PYTHONDONTWRITEBYTECODE   = ""

GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET')

GITHUB_CLIENT_ID = os.getenv('GITHUB_CLIENT_ID')
GITHUB_CLIENT_SECRET = os.getenv('GITHUB_CLIENT_SECRET')

